name: AI Content Update

on:
  schedule:
    - cron: '15 7 * * *'  # Runs every day at 7:15am UTC
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Generate AI Blog Post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_fetch.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/
          git diff --cached --quiet || git commit -m "Automated AI blog post update"
          git push