name: Daily AI Content Generation

# 1) Grant write perms to the GITHUB_TOKEN
permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout with persisted credentials so push can use the token
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true     # <— ensures GITHUB_TOKEN is in .git/config

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai markdown python-slugify

      - name: Run AI fetch script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_fetch.py

      - name: Commit & push new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/
          git diff --quiet --cached || git commit -m "chore: daily AI content (${{ github.event.schedule || 'manual' }})"
          git push
