name: Daily AI Content Generation

on:
  schedule:
    # Runs every day at 08:00 UTC (03:00 CT)
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai markdown

      - name: Run AI fetch script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/ai_fetch.py

      - name: Commit & push new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts/ latest.json
          git commit -m "chore: daily AI content (${ { github.event.schedule || 'manual' } })" || echo "No changes"
          git push
